apiVersion: apps/v1
kind: Deployment
metadata:
  name: pdf-parser-api
  labels:
    app: pdf-parser
    component: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pdf-parser
      component: api
  template:
    metadata:
      labels:
        app: pdf-parser
        component: api
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: api
        image: ${REGISTRY}/pdf-parser:${TAG}
        imagePullPolicy: Always
        args: ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--workers", "2"]
        ports:
        - containerPort: 8000
          name: http
        - containerPort: 8001
          name: metrics
        resources:
          requests:
            cpu: 500m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        env:
        - name: APP_LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: pdf-parser-config
              key: APP_LOG_LEVEL
        - name: MAX_QUEUE_SIZE
          valueFrom:
            configMapKeyRef:
              name: pdf-parser-config
              key: MAX_QUEUE_SIZE
        - name: PDF_CHUNK_SIZE
          valueFrom:
            configMapKeyRef:
              name: pdf-parser-config
              key: PDF_CHUNK_SIZE
        - name: PDF_CHUNK_OVERLAP
          valueFrom:
            configMapKeyRef:
              name: pdf-parser-config
              key: PDF_CHUNK_OVERLAP
        - name: OCR_ENABLED
          valueFrom:
            configMapKeyRef:
              name: pdf-parser-config
              key: OCR_ENABLED
        - name: S3_ENDPOINT_URL
          valueFrom:
            configMapKeyRef:
              name: pdf-parser-config
              key: S3_ENDPOINT_URL
        - name: S3_BUCKET_NAME
          valueFrom:
            configMapKeyRef:
              name: pdf-parser-config
              key: S3_BUCKET_NAME
        - name: S3_REGION
          valueFrom:
            configMapKeyRef:
              name: pdf-parser-config
              key: S3_REGION
        - name: S3_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: pdf-parser-secrets
              key: S3_ACCESS_KEY
        - name: S3_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: pdf-parser-secrets
              key: S3_SECRET_KEY
        - name: CELERY_BROKER_URL
          valueFrom:
            secretKeyRef:
              name: pdf-parser-secrets
              key: CELERY_BROKER_URL
        - name: CELERY_RESULT_BACKEND
          valueFrom:
            secretKeyRef:
              name: pdf-parser-secrets
              key: CELERY_RESULT_BACKEND
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: pdf-parser-secrets
              key: REDIS_URL
        livenessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 30
          periodSeconds: 20
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /health
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 3
      securityContext:
        seccompProfile:
          type: RuntimeDefault
        allowPrivilegeEscalation: false
      nodeSelector:
        workload-type: api 