apiVersion: v1
kind: Secret
metadata:
  name: pdf-parser-secrets
type: Opaque
stringData:
  S3_ACCESS_KEY: "your-access-key"
  S3_SECRET_KEY: "your-secret-key"
  CELERY_BROKER_URL: "amqp://user:password@rabbitmq:5672//"
  CELERY_RESULT_BACKEND: "redis://:password@redis:6379/0"
  REDIS_URL: "redis://:password@redis:6379/0" 